### PR TITLE
add map circle feature

### PR DESCRIPTION
**Pull request by woodenh**

### CODE REVIEW

**Comment by woodenh** [comment]
// simple example in Kotlin //

companion object {
    val COL_CIRCLE_LINE = Color( 0.1, 0.1, 0.1, 0.5 ) // dark grey
    val COL_CIRCLE_FILL = Color( 0.4, 0.4, 0.4, 0.5 ) // light grey
}

// to create
val fenceCircle = MapCircle(Coordinate(fence.latitude, fence.longitude), fence.radius)
                        .setVisible( true )
                        .setColor( COL_CIRCLE_LINE )
                        .setFillColor( COL_CIRCLE_FILL )

// to add
this.mapView.addMapCircle( fenceCircle )

// to remove
this.mapView.removeMapCircle( fenceCircle )

**Comment by woodenh** [comment]
Thanks for the trying and your comments.

Yes, right. I noticed it as well, and am trying to fix it, but it's not working well.
When the zoom rate is changed, some circles are disappearing from the map, which I couldn't figure it out.
Could you please have a look at the recent commit?
If there is no way to fix it, please merge it and leave it as known issue.

**Comment by sothawo** [comment]
the reaction to the resolution change should be done in the Javascript part, I merged the PR, but will undo this commit for the zoom change and have a look at this. Thanks again for your contribution!

**Comment by sothawo** [comment]
just a short notice: I implemented the scaling of the circles when the resolution is changed. I added corresponding code to the demo application. I now need to add this to the 1.x branch for Java 8 as well, and then will release a version with this code- probably tomorrow evening.

**Comment by woodenh** [comment]
Thanks for letting me know. That sounds great. I'm looking forward the code soon.
Have a great week!

**Pull request merged**
